### ISSUE TITLE
plugins.gradle.org has no 0.36 version

### ISSUE THREAD

**Issue by glebsts** [classmethod/gradle-aws-plugin#126]
https://plugins.gradle.org/m2/jp/classmethod/aws/gradle-aws-plugin/0.36/
any file gives
&lt;Message&gt;The specified key does not exist.&lt;/Message&gt;
😿

**Comment by k3mist** [comment]
Can we please fix this to get https://github.com/classmethod/gradle-aws-plugin/pull/118?

**Comment by k3mist** [comment]
temporary fix is to add `jcenter()` to buildscript repos

**Comment by ericraymond** [comment]
Any update on this.  The repo is corrupted.

**Comment by dai0304** [comment]
v0.37 is released.
Please try the latest version!

**Comment by wreulicke** [comment]
Congratulation 🎉
