### ISSUE TITLE
this change has introduced a bug: now ProfileCredentialsProvider is only added if profileName is explicitly specified. In my setup I use profiles, but I don't want to specify it in build.gradle, instead I have AWS_PROFILE env variable set. This used to work and no longer does, so I had to downgrade to 0.39 for now

### ISSUE THREAD

**Issue by fedork** [classmethod/gradle-aws-plugin#179]
this change has introduced a bug: now ProfileCredentialsProvider is only added if profileName is explicitly specified. In my setup I use profiles, but I don't want to specify it in build.gradle, instead I have AWS_PROFILE env variable set. This used to work and no longer does, so I had to downgrade to 0.39 for now

_Originally posted by @fedork in https://github.com/classmethod/gradle-aws-plugin/pull/176/review_comment/create_

**Comment by fedork** [comment]
@dai0304 @ImFlog could you take a look and get this fixed? For now I have to downgrade to 0.39... I guess I could make a PR myself if that helps, let me know

**Comment by dai0304** [comment]
OK, I'll revert #176 on #180.

@ImFlog Re-PR is welcome

**Comment by ImFlog** [comment]
I think the issue comes from the fact that the DefaultAWSCredentialsProviderChain was removed and uses the `ProfileCredentialsProvider()` in the provider chain.
I'm pushing a new PR to fix this by appending new providers to the default one.
