### ISSUE TITLE
Feature request # vpc support

### ISSUE THREAD

**Issue by kambeena** [classmethod/gradle-aws-plugin#29]
Lambda support to access vpc resources. The function migration needs extra parameters like subnet ids, vpc info etc. to support this feature. Can you please add.

**Comment by glebsts** [comment]
As it turned out I really need vpc support for lambda deploying, I hope to PR this changeset (together with 'publish' property support) here soon, but first small CR in my local repo. Stay tuned.

**Comment by glebsts** [comment]
@dai0304 this issue can be closed.
