### ISSUE TITLE
Configurable wait period for long running cloudformation tasks

### ISSUE THREAD

**Issue by zencodeuk** [classmethod/gradle-aws-plugin#40]
How can I configure this?

https://github.com/classmethod/gradle-aws-plugin/blob/develop/src/main/java/jp/classmethod/aws/gradle/cloudformation/AmazonCloudFormationWaitStackStatusTask.java#L60

Thanks

**Comment by zencodeuk** [comment]
awsCfnWaitStackComplete.loopTimeout = 10800 // = 3hr

**Comment by dai0304** [comment]
For example, you can configure this property as following:
```
awsCfnWaitStackComplete.loopTimeout = 10800 // = 3hr
awsCfnWaitStackDeleted.loopTimeout = 10800 // = 3hr
```

These configuration must be written after `apply plugin: "jp.classmethod.aws.cloudformation"`.
Application of this plugin define `awsCfnWaitStackComplete` and `awsCfnWaitStackDeleted` task.  These are instance of AmazonCloudFormationWaitStackStatusTask.

**Comment by zencodeuk** [comment]
:+1:
