### ISSUE TITLE
Does gradle-aws-plugin support using DefaultAWSCredentialsProviderChain?

### ISSUE THREAD

**Issue by stewartbryson** [classmethod/gradle-aws-plugin#45]

**Comment by dai0304** [comment]
gradle-aws-plugin uses custom AWSCredentialsProviderChain.  This chain behaves as a super set of DefaultAWSCredentialsProviderChain.

https://github.com/classmethod/gradle-aws-plugin/blob/develop/src/main/java/jp/classmethod/aws/gradle/AwsPluginExtension.java#L74
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java#L39
