### ISSUE TITLE
Support CloudFormation stack tags

### ISSUE THREAD

**Issue by opajonk** [classmethod/gradle-aws-plugin#52]
The CreateStackRequest which is instantiated in the AmazonCloudFormationMigrateStackTask can handle tagging. However, there is no possibility to enter the tags into the process. That would be a really nice feature.

**Comment by atschabu** [comment]
Coincidentally I was already working on this feature. Will create a pull-request later today.

**Comment by dai0304** [comment]
Fixed in 0.30
