### ISSUE TITLE
Ability to Set ACL during upload and creation

### ISSUE THREAD

**Issue by DomAmato** [classmethod/gradle-aws-plugin#56]
seems like it could be handled similarly to how metadata is for the upload task
https://docs.amazonaws.cn/en_us/AmazonS3/latest/dev/acl-using-java-sdk.html

**Comment by DomAmato** [comment]
Seems someone already beat me to it
https://github.com/naoki-iwami/gradle-aws-plugin/commit/4eb9f7cd96aa63eeaf82bd1508de08e5255542a2

**Comment by isaacaggrey** [comment]
This appears to work for me. I'm going to go ahead and open up a PR for @naoki-iwami and rebase against develop.

**Comment by DomAmato** [comment]
thanks ill close this issue then since it looks like it was pulled in
