### ISSUE TITLE
Invoking lambda with no payload gives NPE

### ISSUE THREAD

**Issue by glebsts** [classmethod/gradle-aws-plugin#70]
https://github.com/classmethod/gradle-aws-plugin/blob/develop/src/main/java/jp/classmethod/aws/gradle/lambda/AWSLambdaInvokeTask.java#L98
if payload is not ByteBuffer, File or Closure, it calls payload.toString();
But according to http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html  payload is not required parameter, so when I was invoking my lambda with InvocationType.Event, I did not set any payload, and it crashed when calling toString() on null.
I'm not sure to be honest, if this is a real bug, but I don't think that setting payload to empty string would be nice when I don't need any payload.
@dai0304 what do you think, should that be fixed, or not? I can send PR if it is considered to be a bug.

**Comment by donalhenry** [comment]
This should be resolved by #83. Was merged to development today by @dai0304.
