### ISSUE TITLE
CloudFormation update tasks should throw an exception if the stack update/create fails

### ISSUE THREAD

**Issue by gcmcnutt** [classmethod/gradle-aws-plugin#79]
Right now, it appears that the CloudFormation update tasks don't throw an error if the stack update fails.

We'd like to change it so a failing update throws an error (e.g. to stop a build process, etc)

(We'll prototype a fix and issue a pull request)

**Comment by tellary** [comment]
This one is done in the #80 pull request. The issue should be closed now.
